// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ProcessFiles(arg1:Array<main.NcmFile>,arg2:string):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;
